[2025-10-26T22:07:45.289+0100] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-26T22:07:45.343+0100] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_hourly_refresh.run_dbt_models manual__2025-10-26T21:07:43.673322+00:00 [queued]>
[2025-10-26T22:07:45.377+0100] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_hourly_refresh.run_dbt_models manual__2025-10-26T21:07:43.673322+00:00 [queued]>
[2025-10-26T22:07:45.378+0100] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-10-26T22:07:45.413+0100] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): run_dbt_models> on 2025-10-26 21:07:43.673322+00:00
[2025-10-26T22:07:45.424+0100] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dbt_hourly_refresh', 'run_dbt_models', 'manual__2025-10-26T21:07:43.673322+00:00', '--job-id', '67', '--raw', '--subdir', 'DAGS_FOLDER/dbt_hourly_refresh_dag.py', '--cfg-path', '/tmp/tmp2huym_we']
[2025-10-26T22:07:45.429+0100] {standard_task_runner.py:105} INFO - Job 67: Subtask run_dbt_models
[2025-10-26T22:07:45.437+0100] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=3492) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-10-26T22:07:45.439+0100] {standard_task_runner.py:72} INFO - Started process 3493 to run task
[2025-10-26T22:07:45.512+0100] {task_command.py:467} INFO - Running <TaskInstance: dbt_hourly_refresh.run_dbt_models manual__2025-10-26T21:07:43.673322+00:00 [running]> on host f229876aebe2
[2025-10-26T22:07:45.683+0100] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Aliostadi' AIRFLOW_CTX_DAG_ID='dbt_hourly_refresh' AIRFLOW_CTX_TASK_ID='run_dbt_models' AIRFLOW_CTX_EXECUTION_DATE='2025-10-26T21:07:43.673322+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-26T21:07:43.673322+00:00'
[2025-10-26T22:07:45.685+0100] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-26T22:07:45.754+0100] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-26T22:07:45.757+0100] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/dbt_project && dbt clean && dbt run --full-refresh']
[2025-10-26T22:07:45.776+0100] {subprocess.py:86} INFO - Output:
[2025-10-26T22:07:56.846+0100] {subprocess.py:93} INFO - [0m21:07:56  Running with dbt=1.8.3
[2025-10-26T22:07:58.818+0100] {subprocess.py:93} INFO - [0m21:07:58  Checking /opt/***/dbt_project/dbt_packages/*
[2025-10-26T22:07:58.837+0100] {subprocess.py:93} INFO - [0m21:07:58  Cleaned /opt/***/dbt_project/dbt_packages/*
[2025-10-26T22:07:58.838+0100] {subprocess.py:93} INFO - [0m21:07:58  Checking /opt/***/dbt_project/target/*
[2025-10-26T22:07:58.848+0100] {subprocess.py:93} INFO - [0m21:07:58  Cleaned /opt/***/dbt_project/target/*
[2025-10-26T22:07:58.850+0100] {subprocess.py:93} INFO - [0m21:07:58  Finished cleaning all paths.
[2025-10-26T22:19:29.674+0100] {job.py:229} INFO - Heartbeat recovered after 698.20 seconds
[2025-10-26T22:19:35.699+0100] {subprocess.py:93} INFO - [0m21:19:35  Running with dbt=1.8.3
[2025-10-26T22:19:36.453+0100] {subprocess.py:93} INFO - [0m21:19:36  Registered adapter: postgres=1.8.2
[2025-10-26T22:19:36.606+0100] {subprocess.py:93} INFO - [0m21:19:36  Unable to do partial parsing because saved manifest not found. Starting full parse.
[2025-10-26T22:19:37.885+0100] {subprocess.py:93} INFO - [0m21:19:37  [[33mWARNING[0m]: Deprecated functionality
[2025-10-26T22:19:37.886+0100] {subprocess.py:93} INFO - The `tests` config has been renamed to `data_tests`. Please see
[2025-10-26T22:19:37.886+0100] {subprocess.py:93} INFO - https://docs.getdbt.com/docs/build/data-tests#new-data_tests-syntax for more
[2025-10-26T22:19:37.886+0100] {subprocess.py:93} INFO - information.
[2025-10-26T22:19:38.407+0100] {subprocess.py:93} INFO - [0m21:19:38  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2025-10-26T22:19:38.408+0100] {subprocess.py:93} INFO - There are 1 unused configuration paths:
[2025-10-26T22:19:38.408+0100] {subprocess.py:93} INFO - - models.intermediters
[2025-10-26T22:19:38.875+0100] {subprocess.py:93} INFO - [0m21:19:38  Found 4 models, 8 data tests, 3 sources, 428 macros
[2025-10-26T22:19:38.881+0100] {subprocess.py:93} INFO - [0m21:19:38
[2025-10-26T22:19:39.105+0100] {subprocess.py:93} INFO - [0m21:19:39  Concurrency: 4 threads (target='dev')
[2025-10-26T22:19:39.106+0100] {subprocess.py:93} INFO - [0m21:19:39
[2025-10-26T22:19:39.125+0100] {subprocess.py:93} INFO - [0m21:19:39  1 of 4 START sql incremental model analytics.int_availability_station_hour ..... [RUN]
[2025-10-26T22:19:39.133+0100] {subprocess.py:93} INFO - [0m21:19:39  2 of 4 START sql incremental model analytics.int_performance_station_hour ...... [RUN]
[2025-10-26T22:19:39.136+0100] {subprocess.py:93} INFO - [0m21:19:39  3 of 4 START sql incremental model analytics.int_quality_station_hour .......... [RUN]
[2025-10-26T22:19:41.714+0100] {subprocess.py:93} INFO - [0m21:19:41  2 of 4 OK created sql incremental model analytics.int_performance_station_hour . [[32mSELECT 3083[0m in 2.58s]
[2025-10-26T22:19:43.427+0100] {subprocess.py:93} INFO - [0m21:19:43  1 of 4 OK created sql incremental model analytics.int_availability_station_hour  [[32mSELECT 710[0m in 4.30s]
[2025-10-26T22:19:48.029+0100] {subprocess.py:93} INFO - [0m21:19:48  3 of 4 OK created sql incremental model analytics.int_quality_station_hour ..... [[32mSELECT 3083[0m in 8.89s]
[2025-10-26T22:19:48.033+0100] {subprocess.py:93} INFO - [0m21:19:48  4 of 4 START sql incremental model analytics.int_quality_linewise_datehour ..... [RUN]
[2025-10-26T22:19:48.592+0100] {subprocess.py:93} INFO - [0m21:19:48  4 of 4 OK created sql incremental model analytics.int_quality_linewise_datehour  [[32mSELECT 395[0m in 0.56s]
[2025-10-26T22:19:48.620+0100] {subprocess.py:93} INFO - [0m21:19:48
[2025-10-26T22:19:48.621+0100] {subprocess.py:93} INFO - [0m21:19:48  Finished running 4 incremental models in 0 hours 0 minutes and 9.74 seconds (9.74s).
[2025-10-26T22:19:48.688+0100] {subprocess.py:93} INFO - [0m21:19:48
[2025-10-26T22:19:48.689+0100] {subprocess.py:93} INFO - [0m21:19:48  [32mCompleted successfully[0m
[2025-10-26T22:19:48.690+0100] {subprocess.py:93} INFO - [0m21:19:48
[2025-10-26T22:19:48.692+0100] {subprocess.py:93} INFO - [0m21:19:48  Done. PASS=4 WARN=0 ERROR=0 SKIP=0 TOTAL=4
[2025-10-26T22:19:49.628+0100] {subprocess.py:97} INFO - Command exited with return code 0
[2025-10-26T22:19:49.679+0100] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-26T22:19:49.680+0100] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dbt_hourly_refresh, task_id=run_dbt_models, run_id=manual__2025-10-26T21:07:43.673322+00:00, execution_date=20251026T210743, start_date=20251026T210745, end_date=20251026T211949
[2025-10-26T22:19:49.744+0100] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-26T22:19:49.784+0100] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-26T22:19:49.786+0100] {local_task_job_runner.py:245} INFO - ::endgroup::
